ARG FROM_IMAGE
FROM ${FROM_IMAGE} AS BASE

ENV GH_VERSION=1.13.1
ENV YQ_VERSION=4.11.2
ENV OC_VERSION=4.12.8
ENV HELM_VERSION=3.11.2
ENV ARGOCD_VERSION=v2.7.4

RUN microdnf install -y git tar gzip openssh-clients jq

RUN rpm -i https://github.com/cli/cli/releases/download/v${GH_VERSION}/gh_${GH_VERSION}_linux_amd64.rpm

RUN curl -s -o /tmp/yq -L https://github.com/mikefarah/yq/releases/download/v${YQ_VERSION}/yq_linux_amd64 && cd /usr/bin && cp /tmp/yq . && chmod a+x /usr/bin/yq && rm -f /tmp/yq
RUN curl -s -o /tmp/oc.tar.gz -L https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/${OC_VERSION}/openshift-client-linux-${OC_VERSION}.tar.gz && cd /usr/bin && tar -xvzf /tmp/oc.tar.gz && chmod a+x /usr/bin/oc && chmod a+x /usr/bin/kubectl && rm -f /tmp/oc.tar.gz
RUN curl -s -o /tmp/helm.tar.gz -L https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz && cd /usr/bin && tar -xvzf /tmp/helm.tar.gz linux-amd64/helm && mv /usr/bin/linux-amd64/helm /usr/bin/helm && rm -rf /usr/bin/linux-amd64 && chmod a+x /usr/bin/helm && rm -f /tmp/helm.tar.gz
RUN curl -s -o /tmp/argocd -L https://github.com/argoproj/argo-cd/releases/download/${ARGOCD_VERSION}/argocd-linux-amd64 && cd /usr/bin && cp /tmp/argocd . && chmod a+x /usr/bin/argocd && rm -f /tmp/argocd

